feat(select): select an option from a list of options
naveteam/saturn pull request #101
Opened 2020-08-19 15:51 UTC by italonolasco

## Descreva o que foi feito neste PR (Obrigatório)
Criação do componente Select e sua story no Storybooks.

## Cards relacionados e links externos (Obrigatório)
Jira: https://naveteam.atlassian.net/browse/DSYS-333
Figma: https://www.figma.com/file/O3bKxIcsj2rc1FNIRclJyT/Saturn-System?node-id=242%3A117

2020-08-19 18:27 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +import { ExpandMore, ExpandLess, Check } from '../../icons'
Aqui acho que seria interessante usar nosso componente de Icon invés de importar direto da pasta que contem os icones

2020-08-19 18:37 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +    const outsideAlerter = ref => {
Pelo o que eu entendi tu criou essa função com o effect dentro pra fazer o click outside e chama ela no render do componente. Assim tu acaba não utilizando a real função do useEffect que é ser chamado no primeiro render ou quando a dependencia dele mudar!

Sugiro de alterar pra algo assim:
![Screenshot from 2020-08-19 15-35-31](https://user-images.githubusercontent.com/54547117/90676035-b10e4a00-e231-11ea-9e60-ef9c5cc388cc.png)

Outra sugestão é que temos uma lib de hook que contém funções como essa, talvez seja legal usarmos no nosso design system, o @eduardobittencourt pode nos ajudar a decidir isso.

2020-08-19 18:44 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +        {!focus && <Message>{caption}</Message>}
Seria bom testar se o caption existe, para caso não tenha, não mostrar nada.

2020-08-19 18:45 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +    false: css``
Acredito que essa false não seja necessário, ja que ele só vai inserir estilos caso passe no teste.

2020-08-19 18:46 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +    false: css``
Aqui seria a mesma coisa

2020-08-19 18:47 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +        background-color: ${({ quiet }) => (quiet ? '#fff' : '#F5F5F5')};
como usamos o xstyled tu pode passar o nome correspondente a cor aqui
```suggestion
        background-color: ${({ quiet }) => (quiet ? 'white' : 'gray.100')};
```

2020-08-19 18:49 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +const IconCheck = styled(Check)`
Aqui se aplica ao comentario de usar nosso componente de icon, assim tu pode passar essas propriedades pra ele sem ter que criar um styled do teu svg

2020-08-19 18:51 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +  color: ${({ filled }) => (filled ? '#212121' : '#757575')};
Aqui tu pode acessar com o nome das cores.

2020-08-19 18:55 UTC, italonolasco commented on src/components/Select/Select.jsx
> +    false: css``
Sem esse false o console.log do navegador fica acusando erro, o Edu sugeriu eu adicionar esse false no TextField também.

2020-08-19 18:57 UTC, italonolasco commented on src/components/Select/Select.jsx
> +        background-color: ${({ quiet }) => (quiet ? '#fff' : '#F5F5F5')};
Foi como tentei inicialmente, mas exatamente neste tipo de declaração onde utilizo um if ternário e um $ para passar a cor, ele não pega a referência para as cores, como o "gray.100". Só consegui resolver enviando a cor diretamente.

2020-08-19 18:58 UTC, italonolasco commented on src/components/Select/Select.jsx
> +  color: ${({ filled }) => (filled ? '#212121' : '#757575')};
Mesma coisa que na 113, ele não pega a referência nesse tipo de declaração. Alguma sugestão de como resolver?

2020-08-19 19:01 UTC, italonolasco commented on src/components/Select/Select.jsx
> +    const outsideAlerter = ref => {
Show!! Vou testar! Uma das partes mais chatas do componente foi fazer esse comportamente. Sobre o hook, acredito que era exatamente o que o Edu queria evitar.

2020-08-19 19:31 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +    const outsideAlerter = ref => {
ah massa! Talvez seja legal criar uma pasta com essas funções pq podemos precisar em outro componente. Acho valido a gente trocar uma ideia sobre tb

2020-08-19 19:36 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +        background-color: ${({ quiet }) => (quiet ? '#fff' : '#F5F5F5')};
cara realmente não sei, talvez pegar o theme nessa função seja uma saida, vou dar uma olhada na doc do xstyled pra ver se tem algo tb. Mas é mal usar a cor direto ai pq caso a paleta de cores seja alterada em algum momento não precisamos passar em todos componentes e alterar eles separadamente

2020-08-19 19:54 UTC, rbschumacher commented on src/components/Select/Select.jsx
> +        background-color: ${({ quiet }) => (quiet ? '#fff' : '#F5F5F5')};
Acredito que tu precisa disso https://xstyled.dev/docs/system-utilities/#theme-getters.

2020-08-20 11:48 UTC, italonolasco commented on src/components/Select/Select.jsx
> +        {!focus && <Message>{caption}</Message>}
Bom dia schumacher, acabei de testar isso. Desta forma que está implementado, caso não exista o caption, ele não renderiza o <Message>, logo ele não mostra nada, como esperado. Tu acha que devo implementar dessa forma:
{!focus && caption && <Message>{caption}</Message>}

Ou não há necessidade?

2020-08-28 16:49 UTC, rcandia commented on src/components/Select/Select.jsx
> +        {!focus && <Message>{caption}</Message>}
Concordo com o @rbschumacher , nesse caso ele não tem nenhum valor padrão para caption, correto? Então pode ser que ele mostre algum erro dentro do console caso tente mostrar algo que não existe, ou até mesmo quebrar a aplicação.

2020-08-28 16:50 UTC, rcandia commented on src/components/Select/Select.jsx
> +        <Container tabIndex='0'>
Essa prop tabIndex é usado em algum lugar? Se sim, qual a função dela? Procurei dentro do código e não consegui achar

2020-08-28 16:50 UTC, rcandia commented on src/components/Select/Select.jsx
> +            <SelectBase tabIndex='-1' value={optionSelected} onChange={handleChange} filled={filled} ref={ref}>
Tem aqui também

2020-09-02 12:00 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +    const [filled, setFilled] = useState(false)
Acho que esse estado não é necessário. Dá pra usar o `!! optionSelected ` no lugar.

2020-09-02 12:08 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +    const [focus, setFocus] = useState(false)
Esse estado é o que controla a abertura e fechamento no componente, correto?

O que tu acha de usar uma nomenclatura do tipo `isOpened` ou algo que indique realmente essa funcionalidade?

2020-09-02 12:08 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +              <Icon icon='ExpandLess' color='gray.800' />
Acho que somente a props de icon pode ser condicionar nesse caso

2020-09-03 16:14 UTC, gcdpinho requested changes

2020-09-03 16:14 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +    useEffect(() => {
Alterar para lib de hooks da nave([link](https://github.com/naveteam/prometheus/blob/develop/src/hooks/useClickOutside.js)).

2020-09-03 16:14 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +
Adicionar hook para fechar no esc

2020-09-11 16:09 UTC, gcdpinho submitted a review, later dismissed

2020-09-11 16:10 UTC, rbschumacher approved these changes

2020-09-14 12:06 UTC, rcandia submitted a review, later dismissed

2020-09-16 11:55 UTC, rcandia submitted a review, later dismissed

2020-09-16 12:20 UTC, gcdpinho approved these changes

2020-09-17 01:13 UTC, sblucas97 commented on src/stories/Select.stories.mdx
> +        options={[
daria pra definir uma pastinha nomeada `utils` onde ficaria tudo que é dado que serve de exemplo nesses stories, onde nesse caso seria criado um arquivo como `optionsSelect.js` e ele iria exportar esse array de opções

nesse caso tu iria usar ele 3 vezes nesse arquivo

criando esse arquivo e definindo esse array, tu até iria conseguir adicionar no final do md algo do tipo:

'foi utilizado esse array nos exemplos acima:

```
const selectOptionsArray = [
          {
            name: 'Name 1',
            description: 'Dev A1'
          },
          {
            name: 'Name 2',
            description: 'Dev A2'
          },
          {
            name: 'Name 3',
            description: 'Dev A3'
          },
          {
            name: 'Name 4',
            description: 'Dev B1'
          },
          {
            name: 'Name 5',
            description: 'Dev B2'
          },
          {
            name: 'Name 6',
            description: 'Dev B3'
          },
          {
            name: 'Name 7',
            description: 'Dev C1'
          },
          {
            name: 'Name 8',
            description: 'Dev C2'
          }
        ]
```
'

2020-09-17 11:50 UTC, italonolasco commented on src/components/Select/index.js
> +import Select from './Select'
Esse aqui eu segui o padrão de todos outros componentes

2020-09-17 11:53 UTC, italonolasco commented on src/stories/Select.stories.mdx
> +        options={[
@eduardobittencourt tu acha interessante criar uma utils pra estes casos onde precisamos passar testes maiores e/ou mais complexos?

2020-09-17 12:45 UTC, italonolasco commented on src/components/Select/Select.jsx
> +Select.defaultProps = {
Cara, pela documentação, só não vai ser mostrado label caso a variant "quiet" seja passada. Mas acho uma boa sim, caso o dev que esteja usando o Select esqueça de passar, não quebra a aplicação, como tu disse. Boa! Vou fazer

2020-09-17 12:48 UTC, italonolasco commented on src/components/Select/Select.jsx
> +const SelectContainer = styled(Flex)`
Achei semanticamente mais bonito cara. Vou dale! Valeu a dica.

2020-09-17 13:17 UTC, sblucas97 commented on src/components/Select/index.js
> +import Select from './Select'
Tranquilo, eu até comentei nos outros prs sobre a gente modificar esse padrão a partir de agora e depois abrir um pr pra modificar os que faltaram

2020-09-18 10:19 UTC, sblucas97 approved these changes

2020-09-21 13:43 UTC, gcdpinho approved these changes

2020-09-21 14:24 UTC, merged