feat(link): add link component
naveteam/saturn pull request #103
Opened 2020-08-19 19:34 UTC by CaaioSB

## Descreva o que foi feito neste PR
Criado o component Link escalável, no qual pode ser utilizado para qualquer outro tipo de Link, tendo como ênfase o Next Link e o Gatsby Link 

## Cards relacionados e links externos
[Jira](https://naveteam.atlassian.net/browse/NTD-26)
[Figma](https://www.figma.com/file/O3bKxIcsj2rc1FNIRclJyT/Saturn-System?node-id=18%3A1)

2020-08-24 11:30 UTC, eduardobittencourt commented on src/components/Link/Link.jsx
> +import Typography from './../Typography/Typography'
Fala @rcandia ! Cara, num primeiro momento eu diria a mesma coisa, mas isso pode gerar dependência circular, o que não é o ideal (quando tu importa do `index.js`, ele carrega todos os componentes pra gerar o bundle, e carregando todos os componentes ele vai chamar novamente o Link, por exemplo, que por sua vez vai carregar novamente todo o `index.js`, e isso fica num ciclo :( acho que nesse caso tem que manter dessa maneira que o @CaaioSB usou, e adaptar isso nos componentes anteriores (my bad n ter iniciado esse padrão já)

2020-08-24 13:16 UTC, CaaioSB commented on src/components/Link/Link.jsx
> +import Typography from './../Typography/Typography'
Opa, muito obrigado pela explicação @eduardobittencourt , eu mantive o código igual, fiz somente alterações referente ao css, quaisquer outra alteração e dica por favor, me enviar.

2020-08-30 22:55 UTC, eduardobittencourt commented on src/components/Link/Link.jsx
> +import Typography from './../Typography/Typography'
na verdade pensando melhor nesse import, acho que é interessante mantermos o import direto do componente ao invés do `index.js`, mas ao invés de utilizar o caminho relativo vamos usar o caminho absoluto do componente
```
import Typography from 'components/Typography'
```

2020-08-30 23:03 UTC, eduardobittencourt commented on src/components/Link/Link.jsx
> +      <Base {...mountPath} passHref to={to} target={target}>
ainda nessa linha, nesse caso nós não precisamos do `to={to}` pq vc ta passando o spread de `mountPath` pro teu componente. Esse `mountPath` é quem vai definir tanto o nome da prop de utilizar no Link quanto o valor que ela vai assumir.

Por exemplo: se vc passar `to='https://nave.rs` e `propPath='href'`, o `mountPath` vai ser basicamente `href='https://nave.rs'`, e isso é o que vai ser passado para os nossos componentes.

2020-08-30 23:15 UTC, eduardobittencourt commented on src/components/Link/Link.jsx
> +          )}
```suggestion
          {component ? (
            <a color={color} target={target}>
              {children}
            </a>
          ) : (
            children
          )}
```

2020-08-30 23:17 UTC, eduardobittencourt commented on src/components/Link/Link.jsx
> +        <Label fontFamily='Open Sans' m={0} p={0} alignItems='center' color={color} as={as}>
esse `Label` provavelmente não esteja pegando os estilos por causa da prop `as` que é interpretada pelo xStyled como um modifier. Podes tentar alterar o nome dessa prop para `forwardedAs` e possivelmente o resto do CSS do `Typography` volta a funcionar. Com isso, podes remover o `fontFamily`.

2020-08-30 23:19 UTC, eduardobittencourt commented on src/components/Link/Link.jsx
> +Link.propTypes = {
as PropTypes dos componentes não podem ser textos. devem ser sempre propriedades do próprio `PropTypes`. Nos 3 casos onde foi colocado texto, substituir por `PropTypes.string`. As informações que foram colocadas como string podem ser adicionadas na documentação do componente

2020-08-30 23:21 UTC, eduardobittencourt commented on src/stories/Link.stories.mdx
> +import { Typography } from '../../src/components/Typography'
nesse caso (como estamos fora da pasta components) podemos utilizar o import desestruturado de `index.js`.

```suggestion
import { Typography, Link } from '../../src/components'
```

2020-08-31 12:11 UTC, CaaioSB commented on src/components/Link/Link.jsx
> +      <Base {...mountPath} passHref to={to} target={target}>
@eduardobittencourt o passHref é uma propriedade que deve ser passada quando se trata de um Next Link, isso é necessário porque estamos utilizando styled-components, veja na [documentação](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag) a orientação

2020-08-31 12:39 UTC, CaaioSB commented on src/stories/Link.stories.mdx
> +import { Typography } from '../../src/components/Typography'
eu removi o Typography, pois não estou mais utilizando ele, eu mantive da seguinte forma

```suggestion
import { Link } from '../../src/components/Link'
```

Pois se eu por como `import { Link } from '../../src/components'` eu obtenho um erro, tentei averiguar porém não vejo nada fora do normal para acontecer isto
![image](https://user-images.githubusercontent.com/34246280/91720598-c9edf800-eb6d-11ea-935c-b6257a538cf9.png)

2020-09-14 13:27 UTC, rcandia submitted a review, later dismissed

2020-09-17 01:19 UTC, sblucas97 commented on src/components/Link/index.js
> +import Link from './Link'
aqui poderia ficar:
`export { default as Link } from './Link'`

o que tu acha?

2020-09-17 01:24 UTC, CaaioSB commented on src/components/Link/index.js
> +import Link from './Link'
Concordo contigo, em breve mando a alteração

2020-09-18 10:21 UTC, sblucas97 approved these changes

2020-09-22 10:55 UTC, eduardobittencourt submitted a review, later dismissed

2020-09-30 18:07 UTC, devSiso submitted a review, later dismissed

2020-09-30 18:56 UTC, gcdpinho commented on src/components/Link/Link.jsx
> +  ${typography}
Essas propriedades não estão no Typography já?

2020-09-30 19:08 UTC, CaaioSB commented on src/components/Link/Link.jsx
> +  ${typography}
Agora que eu me recordei, eu posso usar o padding e borderRadius pelo próprio styled system que já estida contido no Typography, só não tenho certeza do text-decoration-line.

2020-09-30 20:15 UTC, devSiso approved these changes

2020-09-30 21:51 UTC, vitorwtavares requested changes

2020-09-30 21:51 UTC, vitorwtavares commented on src/stories/Link.stories.mdx
> +<Props of={Link} />
Tem que atualizar o storybook pra versão 6.0, como o @italonolasco tinha instruído umas semanas atrás, aí vai precisar dar um rebase na branch e fazer as mudanças no código. Se precisar de ajuda me chama no slack @CaaioSB.

2020-09-30 21:51 UTC, vitorwtavares commented on src/stories/Link.stories.mdx
> +import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks'
Preview virou Canvas e Props virou ArgsTable, só substituir.

2020-09-30 21:51 UTC, vitorwtavares commented on src/stories/Link.stories.mdx
> +<Meta title='Data Display|Link' />
Data Display|Link virou Data Display/Link, **/** invés de **|**

2020-09-30 21:51 UTC, vitorwtavares commented on src/stories/Link.stories.mdx
> +<Preview>
Preview vira Canvas

2020-09-30 21:51 UTC, vitorwtavares commented on src/stories/Link.stories.mdx
> +</Preview>
Preview vira Canvas

2020-09-30 21:51 UTC, vitorwtavares commented on src/stories/Link.stories.mdx
> +<Props of={Link} />
Props vira ArgsTable

2020-10-01 14:28 UTC, eduardobittencourt commented
@CaaioSB o @vitorwtavares vai te dar uma mão pra passar esse componente adiante :D vcs conseguem alinhar isso?

2020-10-01 17:20 UTC, vitorwtavares approved these changes

2020-10-02 13:38 UTC, italonolasco approved these changes

2020-10-02 13:50 UTC, vitorwtavares approved these changes

2020-10-02 13:50 UTC, merged