Feat/attachment
naveteam/saturn pull request #121
Opened 2020-09-23 14:31 UTC by vitorwtavares

### Descreva o que foi feito neste PR 
Criação da versão inicial do componente Attachment (anexo) e respectiva documentação no storybook.
### Cards relacionados e links externos
- [Card Jira](https://naveteam.atlassian.net/browse/DSYS-371)
- [Figma](https://www.figma.com/file/O3bKxIcsj2rc1FNIRclJyT/Saturn-System?node-id=300%3A1)

2020-09-23 18:34 UTC, italonolasco commented on src/components/Attachment/Attachment.jsx
> +import { space, layout, variant, th } from '@xstyled/system'
variant e th não estão sendo utilizadas, dá pra remover

2020-09-23 18:34 UTC, italonolasco commented on src/components/Attachment/Attachment.jsx
> +const Attachment = ({ name, link, onDownload, onView, onDelete, file, backgroundColor, error, variant, ...props }) => {
...props não estão sendo passadas adiante

2020-09-23 18:34 UTC, italonolasco commented on src/stories/Attachment.stories.mdx
> +import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks'
Nessa versão do storybook Preview virou Canvas e Props virou ArgsTable

2020-09-23 18:34 UTC, italonolasco commented on src/stories/Attachment.stories.mdx
> +<Meta title='Data Display|Attachment' component={Attachment} />
Nessa versão do storybook o | virou /, tipo 'Data Display/Attachment'

2020-09-23 18:34 UTC, italonolasco commented on src/components/Attachment/Attachment.jsx
> +            <Link color={handleErrorColor()} forwardedAs='a' pl='8px' {...(link && { href: link, target: '_blank' })}>
Dá pra passar pl={3}, que ele já pega o padding como 8. Tem um array de paddings dentro de theme/Theme.js. No caso o padding faz parte do array de space. É mais pra seguir o padrão dos outros componentes mesmo essa sugestão. Dá pra seguir esse padrão em todos os arrays que tem lá no theme.js, como fontSize, fontWeight, etc...

2020-09-25 12:18 UTC, italonolasco commented on src/components/Attachment/Attachment.jsx
> +import React, { useState } from 'react'
useState dá pra tirar fora, não ta sendo usad.

2020-09-25 12:24 UTC, italonolasco submitted a review, later dismissed

2020-09-25 15:26 UTC, devSiso commented on src/components/Attachment/Attachment.jsx
> +  name: PropTypes.string,
essa prop não tem um valor default, nesse caso deveria ser .isRequired, não?

2020-09-25 15:26 UTC, devSiso commented on src/components/Attachment/Attachment.jsx
> +  link: PropTypes.string,
O mesmo aqui

2020-09-25 19:16 UTC, vitorwtavares commented on src/components/Attachment/Attachment.jsx
> +  link: PropTypes.string,
Na verdade nenhum deles é required, tu tem que ter algum deles no caso, ou name, ou link ou file, se tiver link ou file + name o name toma precedência mas se não tiver ele usa o nome do arquivo ou do link passado, então a princípio tá certo assim, o name é só pra renomear se não quiser que fique o nome padrão do arquivo ou do link.

2020-09-28 13:07 UTC, gcdpinho requested changes

2020-09-28 13:07 UTC, gcdpinho commented on src/components/Attachment/Attachment.jsx
> +  const bytesToSize = bytes => {
Acho que essa função pode ficar fora do componente

2020-09-28 13:17 UTC, vitorwtavares commented on src/components/Attachment/Attachment.jsx
> +  const bytesToSize = bytes => {
@gcdpinho Posso botar num arquivo separado lá na pasta utils e só importar, o que tu acha?

2020-09-29 12:53 UTC, gcdpinho commented on src/components/Attachment/Attachment.jsx
> +  const bytesToSize = bytes => {
Pode ser também. Mas também pode ser no mesmo arquivo, mas fora do render do componente.

2020-09-29 13:17 UTC, rbschumacher commented on src/components/Attachment/Attachment.jsx
> +                {handleName()}{' '}
aqui pra não ficar o `{' '}` acho que da pra usar o `&nbsp;` só pra usar html pra isso

2020-09-29 13:17 UTC, rbschumacher commented on src/components/Attachment/Attachment.jsx
> +                <StyledIcon icon='delete-outline' onClick={onDelete} color={handleErrorColor()} />
é necessário esse `handleErrorColor`? Pq esse teste de `error && variant === 'upload'` não é o mesmo feito dentro dessa função?

2020-09-30 19:49 UTC, vitorwtavares commented on src/components/Attachment/Attachment.jsx
> +                {handleName()}{' '}
Na verdade nem tava usando mais esse espaço em branco, agora fui resolver isso e notei isso, já retirei aqui.

2020-09-30 20:06 UTC, vitorwtavares commented on src/components/Attachment/Attachment.jsx
> +                <StyledIcon icon='delete-outline' onClick={onDelete} color={handleErrorColor()} />
Acredito que sim, porque essa função é usada em alguns outros lugares e essa condicional aí não tá retornando uma cor, é um teste separado só pra determinar se vai ter um ícone de visualizar ou não (no caso de não ter erro).

2020-10-02 19:41 UTC, devSiso submitted a review, later dismissed

2020-10-05 13:12 UTC, rbschumacher commented on src/components/Attachment/index.js
> +export default Attachment
acredito que o padrão ta ficando como `export { default as Attachment } from './Attachment`

2020-10-05 13:27 UTC, rbschumacher submitted a review, later dismissed

2020-10-05 14:04 UTC, devSiso submitted a review, later dismissed

2020-10-05 14:06 UTC, vitorwtavares commented
@all-contributors please add vitorwtavares for code, maintenance, review and doc

2020-10-05 14:16 UTC, vitorwtavares commented
@all-contributors please add vitorwtavares for code, maintenance, review and doc

2020-10-05 14:18 UTC, devSiso approved these changes

2020-10-05 14:34 UTC, rbschumacher approved these changes

2020-10-05 16:37 UTC, italonolasco submitted a review, later dismissed

2020-10-05 17:20 UTC, italonolasco approved these changes

2020-10-05 17:30 UTC, devSiso approved these changes

2020-10-06 14:17 UTC, gcdpinho approved these changes

2020-10-06 14:19 UTC, merged

2020-10-06 14:20 UTC, vitorwtavares commented
@all-contributors please add vitorwtavares for code, maintenance, review and docs