Feat/dialog
naveteam/saturn pull request #122
Opened 2020-09-23 15:23 UTC by glauberbrack

**Criação da versão inicial do componente de Dialog/Modal**

Cards relacionados e links externos
[Card Jira](https://naveteam.atlassian.net/secure/RapidBoard.jspa?rapidView=110&projectKey=DSYS&modal=detail&selectedIssue=DSYS-364)
[Figma](https://www.figma.com/file/O3bKxIcsj2rc1FNIRclJyT/Saturn-System?node-id=2018%3A17421)

2020-09-23 18:50 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +  ...props
props não tá sendo passado adiante.

2020-09-23 18:50 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +  useHotKey(() => setClose(false), 'Escape')
eu usei dessa mesma forma que o Glauber, mas agora me surgiu uma dúvida. É vantagem colocar essas funções em um useMemo? @gcdpinho

2020-09-23 18:50 UTC, italonolasco commented on yarn.lock
> +
Pelo que vi, todas dependências do saturn são instaladas como devDependencies.

2020-09-23 18:50 UTC, italonolasco commented on src/stories/Dialog.stories.mdx
> +import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks'
Quando fizer o rebase da develp, trocar o Preview pro Canvas e o Props pro ArgsTable

2020-09-23 18:50 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +                {cancelButton.label ? cancelButton.label : 'Cancelar'}
Pode ser assim {cancelButton?.label}. Pq caso não exista essa propriedade, o label já está setado como 'Cancelar' nas defaultProps. Testei aqui no local e funcionou

2020-09-23 18:50 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +                {actionButton.label ? actionButton.label : 'Adicionar'}
Acho que mesma coisa aqui.

2020-09-23 18:54 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +  useHotKey(() => setClose(false), 'Escape')
No caso seria dentro de um useCallback, não? O useMemo geralmente é pra controlar a mudança de estado de variáveis.

2020-09-23 20:27 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +                {cancelButton.label ? cancelButton.label : 'Cancelar'}
feito

2020-09-23 20:27 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +                {actionButton.label ? actionButton.label : 'Adicionar'}
feito

2020-09-23 20:28 UTC, glauberbrack commented on yarn.lock
> +
feito

2020-09-23 20:28 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +  ...props
removido.

2020-09-23 20:40 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +  useHotKey(() => setClose(false), 'Escape')
Isso! Exato ahahashah

2020-09-28 13:19 UTC, gcdpinho requested changes

2020-09-28 13:19 UTC, gcdpinho commented on src/components/Dialog/Dialog.jsx
> +const Content = styled.div`
Acho que essa div pode ser um componente de Flex

2020-09-28 13:19 UTC, gcdpinho commented on src/stories/Dialog.stories.mdx
> +import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks'
Consegue fazer esse rebase @glauberbrack ?

2020-09-28 13:24 UTC, gcdpinho requested changes

2020-09-28 13:24 UTC, gcdpinho commented on src/components/Dialog/Dialog.jsx
> +      console.log(closed)
esse console é necessário?

2020-09-28 13:24 UTC, gcdpinho commented on src/components/Dialog/Dialog.jsx
> +  font-weight: 1;
Acho que essas propriedades podem ser passadas por props direto no componente, removendo essa necessidade desse styled

2020-09-28 13:51 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +      console.log(closed)
Tinha esquecido dele, valeu!!

2020-09-28 13:56 UTC, glauberbrack commented on src/stories/Dialog.stories.mdx
> +import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks'
Feito

2020-09-28 13:58 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +const Content = styled.div`
Alterado

2020-09-28 14:01 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +  font-weight: 1;
Feito.

2020-10-02 15:12 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +  withBackground,
withBackground nunca está sendo lido. Me corrige se eu estiver errado, mas ele devia ta sendo testado né? TIpo, o background-color depende dele, ou não?

2020-10-02 15:12 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +              {cancelButton?.label ? cancelButton.label : 'Cancelar'}
Acho que aqui não precisa ser passado o : 'Cancelar', já que nas defaultProps já está como cancelar, então caso não seja passado, ele vai colocar o cancelar, ou não?

2020-10-02 15:12 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +              {actionButton?.label ? actionButton.label : 'Adicionar'}
Acho que aqui não precisa ser passado o : 'Adicionar', já que nas defaultProps já está com essa label, então caso não seja passado, ele vai colocar, ou não?

2020-10-02 20:22 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +  withBackground,
Resolvi. Alterei para um propriedade 'withoutOverlay'

2020-10-02 20:22 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +              {cancelButton?.label ? cancelButton.label : 'Cancelar'}
feito

2020-10-02 20:22 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +              {actionButton?.label ? actionButton.label : 'Adicionar'}
feito

2020-10-05 11:38 UTC, devSiso commented on src/components/Dialog/Dialog.jsx
> +  useClickOutside(() => setClose(false), dialogRef)
Faria sentido mudar o nome da função para setOpen? Parece que "setClose(false)" significa que está aberto, porquê eu entendo como close = false, logo, open = true. Se fosse setOpen, nesse caso seria setOpen(false), o que remete à fechado, ao meu ver. O que você acha?

2020-10-05 16:45 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +  useClickOutside(() => setClose(false), dialogRef)
Eu concordo. Lendo tenho o mesmo pensamento.

2020-10-06 01:17 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +  useClickOutside(() => setClose(false), dialogRef)
Minha unica dúvida seria quando a implicação disso com o compente do mdx. O que acham sobre?

2020-10-06 18:03 UTC, devSiso commented on src/components/Dialog/Dialog.jsx
> +  useClickOutside(() => setClose(false), dialogRef)
Poderias me dar um exemplo?

2020-10-06 19:51 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +  useClickOutside(() => setClose(false), dialogRef)
Não entendi o que muda tbm.

2020-10-08 18:33 UTC, devSiso requested changes

2020-10-08 18:33 UTC, devSiso commented on src/components/Dialog/Dialog.jsx
> +  portalRef = document.body,
não rola de colocarmos isso no defaultProps pra mantermos o padrão?

2020-10-08 18:45 UTC, devSiso requested changes
Mover o valor padrão de portalRef para as defaultProps

2020-10-09 03:08 UTC, italonolasco requested changes

2020-10-09 03:08 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +                  <Icon color='gray.800' icon='name' />
Não ta fechando o ícone

2020-10-09 03:08 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +                {cancelButton?.label ? cancelButton.label : 'Cancelar'}
Não ta fechando também, @devSiso Aí fecha normal?

2020-10-09 03:08 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +  display: flex;
Já ta estilizando um Flex, não precisa dessa linha.

2020-10-09 03:08 UTC, italonolasco commented on src/components/Dialog/Dialog.jsx
> +  border-radius: 2;
Isso tudo dá pra passar por Props, no modelo do styled-system.

2020-10-14 00:41 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +                  <Icon color='gray.800' icon='name' />
Arrumadu

2020-10-14 00:41 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +                {cancelButton?.label ? cancelButton.label : 'Cancelar'}
Arrumadu, as well

2020-10-14 00:42 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +  display: flex;
Bem visto! Arrumado

2020-10-14 00:49 UTC, glauberbrack commented on src/components/Dialog/Dialog.jsx
> +  portalRef = document.body,
Feito!

2020-10-14 12:38 UTC, italonolasco approved these changes

2020-10-14 19:36 UTC, closed without merging