Feature/tabs
naveteam/saturn pull request #125
Opened 2020-09-28 13:54 UTC by devSiso

**Descrição da feature**
Esta feature contempla as seguintes mudanças:
Criação do componente **Tabs**;
Criação da documentação do componente **Tabs**;

Cards Relacionados e Links Externos
[Jira](https://naveteam.atlassian.net/browse/DSYS-365)
[Figma](https://www.figma.com/file/O3bKxIcsj2rc1FNIRclJyT/Saturn-System?node-id=719%3A0)

2020-09-28 17:50 UTC, rbschumacher requested changes

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/index.js
> +export default Tabs
Aqui se eu não me engano a gente vai seguir um padrão novo 
`export { default as Tabs } from './Tabs'`

2020-09-28 17:50 UTC, rbschumacher commented on src/utils/debounce/index.js
> +export function debounce(func) {
Eu acredito que nós temos um hook de debounce, ja que instalamos o prometheus no projeto

2020-09-28 17:50 UTC, rbschumacher commented on src/utils/outerWidth/index.js
> +  var width = el.offsetWidth
por que usar var aqui?

2020-09-28 17:50 UTC, rbschumacher commented on .all-contributorsrc
> +    {
Eu acho que temos um robo pra fazer essas changes aqui, o edu roda ele de tempos em tempos

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +import { outerWidth, debounce } from '../../utils'
Por padrão importamos `utils` após o import de componentes

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +import Flex from '../Grid/Flex'
Aqui pode importar assim pra manter o padrão

```suggestion
import { Flex } from '../Grid'
```

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +import { Typography } from '../'
```suggestion
import { Typography } from '../Typography'
```

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +  const [showNavigation, toggleNavigation] = useState(false)
Nós tentamos manter o padrão de states com o set antes, invés do toggle

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +  const handleChange = value => setActiveTab(value)
por que essa funcão pra setar o estado? Não da pra usar o setActiveTab direto?

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +  const [id] = useState(props.id || `tabs-${String(Math.random()).replace(/\./g, '')}`)
não faltou o `setId` aqui?

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +  ${down(
acho que tu não precisa chamar os down's separados. Da pra por tudo junto

2020-09-28 17:50 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +  const bindScroll = () => {
Eu vi que tu ta usando bastante os classNames pra pegar os componentes e fazer alguns cálculos. A função ficou bem confusa pra mim e posso não ter entendido o que ta acontecendo, mas acredito que nós podemos simplificar essa estrutura, se precisar de ajuda só nos chamar

2020-09-29 11:16 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +  const [id] = useState(props.id || `tabs-${String(Math.random()).replace(/\./g, '')}`)
Não é necessário, já que ele só é setado uma vez, quando monta o componente.

2020-09-29 11:16 UTC, devSiso commented on src/components/Tabs/index.js
> +export default Tabs
Show! Vou modificar então.

2020-09-29 11:17 UTC, devSiso commented on src/utils/debounce/index.js
> +export function debounce(func) {
Vou dar uma olhada nisso, não tenho conhecimento da lib. Tens algum link que possa me ajudar?

2020-09-29 11:17 UTC, devSiso commented on src/utils/outerWidth/index.js
> +  var width = el.offsetWidth
control c + control v kkkkk vou trocar pra const

2020-09-29 11:18 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +import { outerWidth, debounce } from '../../utils'
Beleza, vou mover o import.

2020-09-29 11:19 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +  const [showNavigation, toggleNavigation] = useState(false)
Beleza, vou dar uma melhorada nessa nomenclatura, showNavigation não me agrada na real...

2020-09-29 11:22 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +  const handleChange = value => setActiveTab(value)
Dá sim! Mas eu sempre uso assim pois podem surgir callbacks ou alguma outra execução no evento em questão, e prefiro deixar isso fora do JSX por uma questão de legibilidad. Vou dar uma olhada nos padrões do projeto, se já estamos usando direto eu coloco a chamada no jsx.

2020-09-29 11:34 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +  ${down(
eu faria algo como: `${down(
    'md',
    css`
      button {
        display: none;
      }
    `,
     'sm',
     css`
      ${NavigationWrapperDirectionVariant}; 
     `
  )}` ?

2020-09-29 11:36 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +  const bindScroll = () => {
Cara, gostaria sim. Foi uma solução de acordo com o tempo q eu tinha, dá pra melhorar sim, porém, no momento não consigo pensar em outra maneira senão as classNames pra gente trabalhar com as propriedades de tamanho dos elementos.

2020-09-29 11:38 UTC, devSiso commented on .all-contributorsrc
> +    {
Ah bom, não sabia hehehe, devo remover? @eduardobittencourt

2020-09-29 11:38 UTC, italonolasco commented on src/utils/debounce/index.js
> +export function debounce(func) {
https://github.com/naveteam/prometheus

2020-09-29 11:40 UTC, devSiso commented on src/utils/debounce/index.js
> +export function debounce(func) {
daoraaa, valeu!!

2020-09-29 12:15 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +  ${down(
Fiz um teste aqui e não rolou, acho que tem que usar separado mesmo.

2020-09-29 12:45 UTC, rbschumacher commented on src/components/Tabs/Tabs.jsx
> +  ${down(
não rola mesmo, mas olhei a doc e como tem dois da pra usar o `breakpoint`, talvez faça mais sentido mas da uma olhada. https://xstyled.dev/docs/system-utilities/

2020-09-29 16:50 UTC, devSiso commented on src/utils/debounce/index.js
> +export function debounce(func) {
Gente, dei uma testada aqui no prometheus e ele não aceita um callback no useDebounce, pra usar do jeito que é necessário precisaria modificar o prometheus, pelo DSYS ser um mvp vou manter assim até que seja atualizado no prometheus, daí modificamos isso. @italonolasco @rbschumacher

2020-09-29 17:00 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +  const bindScroll = () => {
@gcdpinho te mencionando pra caso tu queira contribuir com a melhoria dessa função, já que conversamos sobre essa função na reunião de hoje.

2020-09-30 20:16 UTC, italonolasco commented on src/stories/Tabs.stories.mdx
> +          ]}
Pode colocar isso aqui dentro de um `tabsList` ou `tabsOptions` na pasta utils, igual foi feito com a lista de opções do Select.

2020-09-30 20:16 UTC, italonolasco commented on src/stories/Tabs.stories.mdx
> +          ]}
aqui também.

2020-09-30 20:20 UTC, devSiso commented on src/stories/Tabs.stories.mdx
> +          ]}
Não vejo necessidade, acredito que assim fique mais fácil de visualizar no storybook o objeto que a propriedade espera. Se eu deixar em outro local e fizer um import a pessoa só com o storybook não vai ter um exemplo prático do objeto esperado. O que tu acha?

2020-09-30 20:20 UTC, devSiso commented on src/stories/Tabs.stories.mdx
> +          ]}
Respondi acima.

2020-09-30 20:31 UTC, italonolasco reviewed
Acho que tu tem um ponto importante aí que eu não tinha pensado. Eu fiz dessa forma no select por sugestão do Lucas. Mas faz sentido que a lista de opções apareça, visto que temos uma documentação, permitindo assim que o dev que for usar saiba como passar

2020-09-30 20:31 UTC, italonolasco commented on src/components/Tabs/Tabs.jsx
> +import styled, { css, up, down, breakpoints } from '@xstyled/styled-components'
breakpoint não ta sendo usado, pode remover

2020-09-30 20:52 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +import styled, { css, up, down, breakpoints } from '@xstyled/styled-components'
boaa, vou remover.

2020-09-30 20:57 UTC, eduardobittencourt commented on .all-contributorsrc
> +    {
opa, pode tirar sim! podes dar uma pesquisada nos PRs pelo all-contributors bot, ele que faz essas adições pra nós, é bem massa

2020-09-30 21:02 UTC, devSiso commented on .all-contributorsrc
> +    {
showw, vou remover. Valeuss!

2020-10-01 00:38 UTC, italonolasco commented on src/components/Tabs/Tabs.jsx
> +}
Aqui não pode ser arrow function para seguir o padrão?

2020-10-01 23:02 UTC, devSiso commented on src/utils/useEventListener/index.jsx
> +import { useRef, useEffect } from 'react'
Salve juju, cara, eu mantive assim pq o correto seria a gente jogar isso lá pro prometheus

2020-10-01 23:04 UTC, devSiso commented on src/utils/outerWidth/index.js
> +  width += parseInt(style.marginLeft) + parseInt(style.marginRight)
`export const outerWidth = el => {
  const style = getComputedStyle(el)
  const width = el.offsetWidth + (parseInt(style.marginLeft) + parseInt(style.marginRight))
  return width
}
export default outerWidth
`
assim?

2020-10-01 23:07 UTC, devSiso commented on src/utils/outerWidth/index.js
> +export function outerWidth(el) {
Boa, pode deixar.

2020-10-01 23:08 UTC, devSiso commented on src/utils/debounce/index.js
> +    timer = setTimeout(func, 200, event)
Belê, vou fazer essa modificação.

2020-10-01 23:42 UTC, devSiso commented on src/components/Tabs/Tabs.jsx
> +const TabBodyContent = styled.div`
Perfect, troquei aqui. valeuss!

2020-10-02 12:10 UTC, vitorwtavares submitted a review, later dismissed

2020-10-02 14:05 UTC, julianoddreis submitted a review, later dismissed

2020-10-02 14:23 UTC, devSiso reviewed
done

2020-10-02 15:12 UTC, rbschumacher requested changes

2020-10-02 15:12 UTC, rbschumacher commented on src/utils/useEventListener/index.jsx
> +  // Create a ref that stores handler
Acho que tu pode remover esses comentários

2020-10-02 15:15 UTC, devSiso commented on src/utils/useEventListener/index.jsx
> +  // Create a ref that stores handler
conversei com o @jpbretanha e concordamos que como essa função vai estar temporariamente no escopo do DSYS seria legal manter pra galera entender a parada, ou melhor dizendo, não vai atrapalhar. Quando passarmos pro prometheus isso, daí podemos remover isso daí pois já vai ter lá a documentação de uso.

2020-10-02 15:42 UTC, rbschumacher approved these changes

2020-10-02 16:45 UTC, vitorwtavares approved these changes

2020-10-02 17:02 UTC, merged