Feat/avatar
naveteam/saturn pull request #130
Opened 2020-10-01 13:44 UTC by italonolasco

**Descrição da Feature**
Componente de avatar, utilizado para usuários e empresas

**Links Relacionados**
- [Figma](https://www.figma.com/file/O3bKxIcsj2rc1FNIRclJyT/Saturn-System)

**Checklist**
Garanto que meu PR contempla os seguintes pré-requisitos

- [x] Os commits estão seguindo o padrão estipulado pelo [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] O código está formatado e lintado utilizando o padrão de [eslint](https://eslint.org/) do projeto
- [X] O PR está atualizado no [Chromatic](https://www.chromatic.com/)
- [X] A implementação foi testada em mais de um ambiente, garantindo a compatibilidade com todos os possíveis casos

2020-10-01 15:12 UTC, rbschumacher requested changes

2020-10-01 15:12 UTC, rbschumacher commented on src/components/Avatar/Avatar.jsx
> +import Flex from '../Grid'
```suggestion
import { Flex } from '../Grid'
```

2020-10-01 15:12 UTC, rbschumacher commented on src/components/Avatar/Avatar.jsx
> +import { Icon, Typography } from '../'
Vamos importar direto das pastas, pra evitar problemas. Acho que ficou definido como padrão

2020-10-01 15:12 UTC, rbschumacher commented on src/components/Avatar/Avatar.jsx
> +  let sizeInPx = '48px'
Tu não acha mais legivel guardar isso em um estado que contem um objeto?  
```
  const [avatarVariants, setAvatarVariants] = ({
     sizeInPx: '48px'
     ...
})
```

2020-10-01 15:12 UTC, rbschumacher commented on src/components/Avatar/Avatar.jsx
> +  switch (status) {
Não acha melhor fazer esses testes dentro de um effect que contém o status e o size como dependencia? E de repente utilizar uma estrutura com if e return pra ficar menos verboso

2020-10-01 21:44 UTC, vitorwtavares submitted a review, later dismissed

2020-10-02 11:38 UTC, italonolasco commented on src/components/Avatar/Avatar.jsx
> +  let sizeInPx = '48px'
Cara, realizei essas changes e notei uma coisa. Como size e status são propriedades externas, ou seja, não são modificadas dentro do componente, toda vez que elas são alteradas, o componente é re-renderizado, o estado inicia com o seus valores padrões novamente (sizeInPX, = 48, color, etc...), e ao passar pelo useEffect, ele realiza as mudanças necessárias (por ex, se o size é huge, ele altera o tamanho do avatar). Dá pra ver de forma muito rápida o componente iniciando com os atributos padrão e sendo modificado. Coisa que não acontecia com o código sem state e effect. Eu particularmente acho que o código fica muito mais fluído sem o state e effect por causa disso que citei. Que tu acha? @rbschumacher

2020-10-02 12:30 UTC, rcandia commented on src/components/Avatar/Avatar.jsx
> +  let sizeInPx = '48px'
O que acha de um useMemo então? Faz mais ou menos o que o state e o effect fazem, porém não é no primeiro render. Poderiam ser 2 memos que contêm os switchs de status e size. Acho que ficaria menos verboso e mais legível, o que acham @rbschumacher @italonolasco ? 
```
const statusProps = useMemo(() => {
  const defaultProps = {
     sizeInPx: '48px',
     ...
  }

  switch (status) {
   case 'away':
      return {
        ...defaultProps,
        statusColor: 'gray.400'
      }
    ...
  }
}, [status])
```

2020-10-02 12:44 UTC, rbschumacher commented on src/components/Avatar/Avatar.jsx
> +  let sizeInPx = '48px'
Acho valido o teste, pq meu medo de deixar os switchs dentro do render é que como o avatar vai aparecer diversas vezes dentro da mesma tela, isso causar muitos re renders e por consequencia diversos testes

2020-10-02 12:58 UTC, italonolasco commented on src/components/Avatar/Avatar.jsx
> +  let sizeInPx = '48px'
Boaaa @rcandia. Vou testar!

2020-10-02 19:58 UTC, rcandia requested changes

2020-10-02 19:58 UTC, rcandia commented on src/components/Avatar/Avatar.jsx
> +    const props = {
Como tu troca todas as props em todos os casos, tu pode deixar essas props como medium/default case  dentro do switch, o que acha?
Além disso, não é preciso desestruturar as props dentro de todos eles, pois tu altera todos os valores, então, tu pode retirar esse objeto daqui e apenas retornar esses valores dentro do medium case

2020-10-02 19:58 UTC, rcandia commented on src/components/Avatar/Avatar.jsx
> +    const props = {
Aqui é o mesmo caso do primeiro switch, acho que não vale a pena usar tantas desestruturações, pois tu realmente usa essas 2 props somente no case 'available'.
Nesse caso acho que tu pode até retirar esse objeto e passar os valores todos que tu necessita dentro do switch, pois tu está sobrescrevendo os valores depois do spread. O que acha?

2020-10-02 20:25 UTC, rcandia commented on src/icons/AvatarBusinessCenter.js
> +function SvgAvatarBusinessCenter(props) {
Tem algum motivo de usar function ao invés de arrow function aqui e nos outros svgs?

2020-10-02 20:52 UTC, italonolasco commented on src/icons/AvatarBusinessCenter.js
> +function SvgAvatarBusinessCenter(props) {
esse é o padrão que está em todos svgs, só segui.

2020-10-05 11:47 UTC, devSiso submitted a review, later dismissed

2020-10-07 11:52 UTC, devSiso approved these changes

2020-10-07 12:00 UTC, rcandia approved these changes

2020-10-07 18:12 UTC, rbschumacher approved these changes

2020-10-07 18:40 UTC, merged